WebSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HouseFlipper.WebSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebSite/Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HouseFlipper.DataAccess.DB;
using HouseFlipper.DataAccess.Models;
using PagedList;
using System.Reflection;
using Google.Maps.Geocoding;
using HouseFlipper.DataAccess;

namespace HouseFlipper.WebSite.Controllers
{
    public class ListingsController : Controller
    {
        private MlsContext db = new MlsContext();
        //private SortDirection sortDirection = SortDirection.None;

        //[HttpGet]
        //public ActionResult AllListings()
        //{
        //    return View(db.Listings);
        //}

        //[HttpGet]
        //public ActionResult AllListings(int page = 1, int pageSize = 10)
        //{
        //    List<MlsRow> listings = db.Listings.OrderBy(x => x.MLNumber).ToList();
        //    PagedList<MlsRow> model = new PagedList<MlsRow>(listings, page, pageSize);
        //    return View(model);
        //}

        // GET: Listings
        //public ActionResult Index()
        //{
        //    return View(db.Listings.Take(5).ToList());
        //}

        public List<Listing> GetActive()
        {
            var listings = from l in db.Listings
                               //where l.StatusValue() == MlsStatus.Active
                           where l.Status.ToLower().Trim() == "act"
                           select l;
            return listings.ToList();
        }

        public ActionResult Index(string sortOrder, string CurrentSort, string currentFilter, string searchString, SortDirection? sortDirection, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            GeoLocationController geoLocCtrl = new GeoLocationController();
            var listings = from l in db.Listings
                           select l;
            if (!String.IsNullOrEmpty(searchString))
            {
                var search = searchString.ToUpper();
                listings = listings.Where(
                    s => s.MLNumber.ToUpper().Contains(search) ||
                         s.Status.ToUpper().Contains(search) ||
                         s.Address.ToUpper().Contains(search) ||
                         s.City.ToUpper().Contains(search) ||
                         s.LegalSubdivisionName.ToUpper().Contains(search) ||
                         s.PostalCode.ToUpper().Contains(search) ||
                         s.CurrentPrice.ToUpper().Contains(search) ||
                         s.SqFtHeated.ToUpper().Contains(search) ||
                         s.LPSqFt.ToUpper().Contains(search) ||
                         s.SPSqFt.ToUpper().Contains(search) ||
                         s.Beds.ToUpper().Contains(search) ||
                         s.FullBaths.ToUpper().Contains(search) ||
                         s.YearBuilt.ToUpper().Contains(search) ||
                         s.Pool.ToUpper().Contains(search) ||
                         s.Taxes.ToUpper().Contains(search) ||
                         s.CloseDate.ToUpper().Contains(search));
            }
            /*
            bool latLongUpdated = false;
            listings.ToList().ForEach(
                (row) =>
                {
                    if(!row.Latitude.HasValue)
                    //if(row.Latitude==0 && row.Longitude==0)
                    {                        
                        var loc = geoLocCtrl.GetLatLong(row.Address + ", " + row.City + ", FL " + " " + row.PostalCode);
                        if (loc != null)
                        {
                            latLongUpdated = true;
                            row.Latitude = loc.Latitude;
                            row.Longitude = loc.Longitude;
                        }
                    }
                }
                );
            if(latLongUpdated)
            {
                db.SaveChanges();
            }*/

            int pageSize = 500;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;



            sortOrder = String.IsNullOrEmpty(sortOrder) ? "MLNumber" : sortOrder;
            ViewBag.CurrentSort = sortOrder;

            IPagedList<Listing> pageList = null;

            switch (sortOrder)
            {
                case "MLNumber":
                    SetSortDirection(sortOrder, CurrentSort, sortDirection, page);
                    if (ViewBag.SortDirection == SortDirection.Descending)
                    {
                        pageList = listings.OrderByDescending
                                (m => m.MLNumber).ToPagedList(pageIndex, pageSize);
                    }
                    else
                    {
                        pageList = listings.OrderBy
                                    (m => m.MLNumber).ToPagedList(pageIndex, pageSize);
                    }

                    break;
                case "Status":
                    SetSortDirection(sortOrder, CurrentSort, sortDirection, page);
                    if (ViewBag.SortDirection == SortDirection.Descending)
                    {
                        pageList = listings.OrderByDescending
                                (m => m.Status).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Descending;
                    }
                    else
                    {
                        pageList = listings.OrderBy
                                (m => m.Status).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Ascending;
                    }
                    break;

                case "Address":
                    SetSortDirection(sortOrder, CurrentSort, sortDirection, page);
                    if (ViewBag.SortDirection == SortDirection.Descending)
                    {
                        pageList = listings.OrderByDescending
                                (m => m.Address).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Descending;
                    }
                    else
                    {
                        pageList = listings.OrderBy
                                (m => m.Address).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Ascending;
                    }
                    break;

                case "City":
                    SetSortDirection(sortOrder, CurrentSort, sortDirection, page);
                    if (ViewBag.SortDirection == SortDirection.Descending)
                    {
                        pageList = listings.OrderByDescending
                                (m => m.City).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Descending;
                    }
                    else
                    {
                        pageList = listings.OrderBy
                                (m => m.City).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Ascending;
                    }
                    break;

                case "CurrentPrice":
                    SetSortDirection(sortOrder, CurrentSort, sortDirection, page);
                    if (ViewBag.SortDirection == SortDirection.Descending)
                    {
                        pageList = listings.ToList().OrderByDescending
                                (m => m.CurrentPriceValue(), new NumericComparer(sortOrder, SortDirection.Descending)).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Descending;
                    }
                    else
                    {
                        pageList = listings.ToList().OrderBy
                                (m => m.CurrentPriceValue(), new NumericComparer(sortOrder, SortDirection.Ascending)).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Ascending;
                    }
                    break;

                default:
                    SetSortDirection(sortOrder, CurrentSort, sortDirection, page);
                    if (ViewBag.SortDirection == SortDirection.Descending)
                    {
                        pageList = listings.ToList().OrderByDescending
                                (m => m, new MlsRowComparer(sortOrder)).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Descending;
                    }
                    else
                    {
                        pageList = listings.ToList().OrderBy
                                (m => m, new MlsRowComparer(sortOrder)).ToPagedList(pageIndex, pageSize);
                        ViewBag.SortDirection = SortDirection.Ascending;
                    }
                    break;

                    // Add sorting statements for other columns

                    //case "Default":
                    //    products = listings.OrderBy
                    //            (m => m.MLNumber).ToPagedList(pageIndex, pageSize);
                    //    sortDirection = SortDirection.Ascending;
                    //    break;

                    //default:
                    //    SetSortDirection(sortOrder, CurrentSort, sortDirection, page);
                    //    if (ViewBag.SortDirection == SortDirection.Descending)
                    //    {
                    //        products = listings.ToList().OrderByDescending
                    //                (m => GetPropertyValue(m,sortOrder)).ToPagedList(pageIndex, pageSize);
                    //        ViewBag.SortDirection = SortDirection.Descending;
                    //    }
                    //    else

WebSite/Views/Flips/ByCommonSubDivision.cshtml
@model IEnumerable<HouseFlipper.DataAccess.Models.FlippedCharacteristics>

@{
    ViewBag.Title = "Flips: Common Subdivision";
}

<h2>Flips: Common Subdivision</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubDivision)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.Beds)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.FullBaths)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.HalfBaths)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.SqFtHeated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.YearBuilt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profit)
        </th>
        <th>
            PurchasePrice
        </th>
        <th>
            SoldPrice
        </th>
        <th>
            ROIP
        </th>
        <th>
            ROIS
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubDivision)
            </td>            
            <td>
                @Html.DisplayFor(modelItem => item.PostFlip.Beds)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostFlip.FullBaths)
            </td>
            <td>
                @Html.DisplayFor(model => item.PostFlip.HalfBaths)
            </td>
            <td>
                @Html.DisplayFor(model => item.PostFlip.SqFtHeated)
            </td>
            <td>
                @Html.DisplayFor(model => item.PostFlip.YearBuilt)
            </td>
            <td>
                @Html.DisplayFor(model => item.Profit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreFlip.PriceStr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostFlip.PriceStr)
            </td>
            <td>
                @Html.DisplayFor(model => item.RoiPurchase)
            </td>
            <td>
                @Html.DisplayFor(model => item.RoiSold)
            </td>
        </tr>
    }

</table>

WebSite/Views/Flips/BySubDivision.cshtml
@model IEnumerable<HouseFlipper.DataAccess.Models.FlippedCharacteristics>

@{
    ViewBag.Title = "Flips: Subdivision";
}

<h2>Flips: Subdivision</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubDivision)
        </th>               
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.Beds)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.FullBaths)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.HalfBaths)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.SqFtHeated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.YearBuilt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profit)
        </th>
        <th>
            PurchasePrice
        </th>
        <th>
            SoldPrice
        </th>
        <th>
            ROIP
        </th>
        <th>
            ROIS
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubDivision)
        </td>               
        <td>
            @Html.DisplayFor(modelItem => item.PostFlip.Beds)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostFlip.FullBaths)
        </td>
        <td>
            @Html.DisplayFor(model => item.PostFlip.HalfBaths)
        </td>
        <td>
            @Html.DisplayFor(model => item.PostFlip.SqFtHeated)
        </td>
        <td>
            @Html.DisplayFor(model => item.PostFlip.YearBuilt)
        </td>
        <td>
            @Html.DisplayFor(model => item.Profit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PreFlip.PriceStr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostFlip.PriceStr)
        </td>
        <td>
            @Html.DisplayFor(model => item.RoiPurchase)
        </td>
        <td>
            @Html.DisplayFor(model => item.RoiSold)
        </td>
    </tr>
}

</table>

WebSite/Views/Flips/ByZip.cshtml
@model HouseFlipper.DataAccess.Models.Zips

@{
    ViewBag.Title = "Flips: Zipcode";
}

<h3>Flips: Zipcode</h3>

@using (Html.BeginForm())
{
    <table class="table">
        <tr>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Zipcode","ByZip", new { sortOrder = "Zipcode"})</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Subdiv", "ByZip", new { sortOrder = "SubdivisionCount" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Flips", "ByZip", new { sortOrder = "Count" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Active", "ByZip", new { sortOrder = "ActiveCount" })</p>
            </th>
            
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Beds", "ByZip", new { sortOrder = "AverageBedsValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Full", "ByZip", new { sortOrder = "AverageFullBathsValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Half", "ByZip", new { sortOrder = "AverageHalfBathsValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Year", "ByZip", new { sortOrder = "AverageYearBuilt" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">Pool</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Purchase", "ByZip", new { sortOrder = "AveragePurchaseValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Sold", "ByZip", new { sortOrder = "AverageSoldPriceValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Profit", "ByZip", new { sortOrder = "AverageProfitValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("SqFt", "ByZip", new { sortOrder = "AverageSqFtHeatedValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Purchase/SqFt", "ByZip", new { sortOrder = "AveragePPSqFtValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("Sold/SqFt", "ByZip", new { sortOrder = "AverageSPSqFTValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("ROI", "ByZip", new { sortOrder = "AverageROIValue" })</p>
            </th>
            <th align="center">
                <p style="text-align: center">@Html.ActionLink("ADOM", "ByZip", new { sortOrder = "AverageADOMValue" })</p>
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.Zipcode)
                </td>
                <td align="center">
                    <p>@Html.ActionLink(@Html.DisplayFor(modelItem => item.SubdivisionCount).ToString(), "Subdivision", new { id = item.Zipcode })</p>
                </td>                
                <td align="center">
                    <p>@Html.ActionLink(@Html.DisplayFor(modelItem => item.Count).ToString(), "FlippedHomes", new { id = item.Zipcode })</p>
                </td>
                <td align="center">
                    <p>@Html.ActionLink(@Html.DisplayFor(modelItem => item.ActiveCount).ToString(), "Homes", new { id = item.Zipcode, filter = "active" })</p>
                </td>
                <td align="center">
                    @*@Html.DisplayFor(modelItem => item.AverageBought.Beds)/@Html.DisplayFor(modelItem => item.AverageSold.Beds)*@
                    @Html.DisplayFor(modelItem => item.AverageBeds)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AverageFullBaths)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AverageHalfBaths)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AverageYearBuilt)
                </td>
                <td align="center">
                    @*@Html.DisplayFor(modelItem => item.Pool)*@
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AveragePurchase)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AverageSoldPrice)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AverageProfit)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AverageSqFtHeated)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AveragePPSqFt)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AverageSPSqFT)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AverageROI)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.AverageADOM)
                </td>
            </tr>
        }

    </table>
}

WebSite/Views/Flips/ByZipNoPool.cshtml
@model IEnumerable<HouseFlipper.DataAccess.Models.FlippedCharacteristics>

@{
    ViewBag.Title = "Flips: Zipcode";
}

<h2>Flips: Zipcode</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Zipcode)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.Beds)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.FullBaths)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.HalfBaths)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.SqFtHeated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PreFlip.YearBuilt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profit)
        </th>
        <th>
            PurchasePrice
        </th>
        <th>
            SoldPrice
        </th>        
        <th>
            ROIP
        </th>
        <th>
            ROIS
        </th>
        <th>
            PreSqFt
        </th>
        <th>
            PostSqFt
        </th>
        <th>
            LP/SqFt
        </th>
        <th>
            SP/SqFt
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Zipcode)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.PostFlip.Beds)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostFlip.FullBaths)
        </td>
        <td>
            @Html.DisplayFor(model => item.PostFlip.HalfBaths)
        </td>
        <td>
            @Html.DisplayFor(model => item.PostFlip.SqFtHeated)
        </td>
        <td>
            @Html.DisplayFor(model => item.PostFlip.YearBuilt)
        </td>
        <td>
            @Html.DisplayFor(model => item.Profit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PreFlip.PriceStr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostFlip.PriceStr)
        </td>        
        <td>
            @Html.DisplayFor(model => item.RoiPurchase)
        </td>
        <td>
            @Html.DisplayFor(model => item.RoiSold)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PreFlip.SqFtHeated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostFlip.SqFtHeated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PreFlip.PriceSqFt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostFlip.PriceSqFt)
        </td>
    </tr>
}

</table>

WebSite/Views/Flips/History.cshtml
@model IEnumerable<HouseFlipper.DataAccess.DB.Listing>

@{
    ViewBag.Title = "History";
}

<h2>History</h2>

<table class="table">
    <tr>
        <th>
            ML #
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            Zip
        </th>
        <th>
            SubDiv
        </th>
        <th>
            SqFt
        </th>
        <th>
            Price
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Beds)
        </th>
        <th>
            Full
        </th>
        <th>
            Half
        </th>
        <th>
            Year
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pool)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.PropertyStyle)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Taxes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CDOM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ADOM)
        </th>
        <th>
            DTC
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.SoldTerms)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.CloseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LPSqFt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SPSqFt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SPLP)
        </th>
        @*<th>
        @Html.DisplayNameFor(model => model.ListOfficeName)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.ListAgentFullName)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.ListAgentID)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.SellingAgentName)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.SellingOfficeID)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.SellingAgentID)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.LSCListSide)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.OfficePrimaryBoardID)
    </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MLNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostalCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LegalSubdivisionName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SqFtHeated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Beds)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullBaths)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HalfBaths)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearBuilt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pool)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.PropertyStyle)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Taxes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CDOM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ADOM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DaystoContract)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.SoldTerms)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.CloseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LPSqFt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SPSqFt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SPLP)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.ListOfficeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ListAgentFullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ListAgentID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SellingAgentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SellingOfficeID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SellingAgentID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LSCListSide)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OfficePrimaryBoardID)
        </td>*@
        <td>
            @Html.ActionLink("Details", "Details", "Listings", new { id=item.Id }, null)
        </td>
    </tr>
}

</table>