WebSite/Controllers/ActiveController.cs
using HouseFlipper.DataAccess.DB;
using HouseFlipper.DataAccess.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace HouseFlipper.WebSite.Controllers
{
    public class ActiveController : Controller
    {
        private static string dataFolder = @"~/App_Data";
        private static string byZipFile = "activezip.json";
        private static string byZipNoPool = "activezip.json";
        private static string byDivFile = "activediv.json";
        private static string byCommDivFile = "activecommdiv.json";
        private static Lazy<List<Listing>> activeHouses =
           new Lazy<List<Listing>>(
               () =>
               {
                   return InitActiveHouses();                   
               });
        private static Lazy<List<Listing>> activeHousesNoPool =
           new Lazy<List<Listing>>(
               () =>
               {
                   return InitActiveHousesNoPool();
               });
        private static Lazy<List<Listing>> activeByDiv =
           new Lazy<List<Listing>>(
               () =>
               {
                   return InitActiveByDiv();
               });

        private static Lazy<List<Listing>> activeByCommDiv =
           new Lazy<List<Listing>>(
               () =>
               {
                   return InitActiveByCommonDiv();
               });

        private static Lazy<Dictionary<string, List<Listing>>> zipActive =
            new Lazy<Dictionary<string,List<Listing>>>(
                ()=>{
                    var lookup = new Dictionary<string, List<Listing>>(StringComparer.OrdinalIgnoreCase);
                    InitActiveHouses(lookup);   
                    return lookup;
                });

        public static List<Listing> ActiveHomes(string zip, double maxPrice)
        {
            //var all =
            //(from el in activeHouses.Value
            //where el.PostalCode==zipcode
            //select el).ToList();

            var list = new List<Listing>();
            if (zipActive.Value.ContainsKey(zip))
            {
                var all = zipActive.Value[zip];
                foreach (var item in all)
                {
                    if (item.CurrentPriceValue() <= maxPrice)
                    {
                        list.Add(item);
                    }
                }
            }
            return list;
        }

        public static List<Listing> ActiveHomes(string zip, double maxPrice, double avgBed, double avgFullBath, double avgHalfBath, double avgSqft)
        {
            var list = new List<Listing>();
            if (zipActive.Value.ContainsKey(zip))
            {
                var all = zipActive.Value[zip];
                foreach (var item in all)
                {
                    if (item.CurrentPriceValue() <= maxPrice &&
                        item.BedsValue()==avgBed &&
                        item.FullBathsValue()==avgFullBath &&
                        item.HalfBathsValue()==avgHalfBath &&
                        item.SqFtHeatedValue()==avgSqft)
                    {
                        list.Add(item);
                    }
                }
            }
            return list;
        }

        public static List<Listing> ActiveHomes(
            string zip, 
            double maxPrice, 
            double avgBed, 
            //double avgFullBath, 
            //double avgHalfBath, 
            double minSqFt, 
            double maxSqFt, 
            int minYear, 
            int maxYear)
        {
            var list = new List<Listing>();
            if (zipActive.Value.ContainsKey(zip))
            {
                var all = zipActive.Value[zip];
                foreach (var house in all)
                {
                    if (house.CurrentPriceValue() <= maxPrice) //criteria #1: price
                    {
                        var houseYear = house.YearBuiltValue();
                        if (minYear <= houseYear && houseYear <= maxYear) //criteria #2: year built
                        {
                            var houseSqft = house.SqFtHeatedValue();
                            if (minSqFt <= houseSqft && houseSqft <= maxSqFt) //criteria #3: sq ft
                            {
                                var minBeds = avgBed;
                                if (minBeds <= house.BedsValue()) //criteria #4: same beds or more
                                {
                                    list.Add(house);
                                }
                            }
                        }
                    }
                }
            }
            return list;
        }

        private static Lazy<List<Listing>> allActive =
            new Lazy<List<Listing>>(
                () => {
                    var target = new ListingsController();
                    var list = target.GetActive();
                    if (list == null)
                    {
                        list = new List<Listing>();
                    }
                    return list;
                });

        public ActionResult Index()
        {            
            return View(allActive.Value);
        }

        // GET: Active
        public ActionResult ByZip()
        {
            string withinStr = ViewBag.WithinPercent;
            double within = .20;
            if (!string.IsNullOrWhiteSpace(withinStr))
            {
                within = double.Parse(withinStr)/100;
            }

            if (within == 20)
            {
                foreach (var item in activeHouses.Value)
                {
                    var data = FlipsController.FlipByZip;
                    CalculateNeededValues(item, data, "zip");
                }
                return View(activeHouses.Value.OrderBy(x => x.PostalCode).ThenBy(x=>x.LegalSubdivisionName));
            }
            else
            {
                var customList = new List<Listing>();
                var data = FlipsController.FlipByZip;
                foreach(var flipChar in data)
                {
                    var zip = flipChar.Zipcode;
                    var preflip = flipChar.PreFlip;
                    var min = -1.0 * within * preflip.Price;
                    var max = (1.0 + within) * preflip.Price;

                    foreach(var active in activeHouses.Value)
                    {
                        var myPrice = active.CurrentPriceValue();
                        if(myPrice>=min && myPrice<=max)
                        {
                            customList.Add(active);
                            CalculateNeededValues(active, data, "zip");
                        }
                    }                    
                }
                return View(customList.OrderBy(x => x.PostalCode).ThenBy(x => x.LegalSubdivisionName));
            }            
        }

        public ActionResult ByZipNoPool()
        {
            string withinStr = ViewBag.WithinPercent;
            double within = .20;
            if (!string.IsNullOrWhiteSpace(withinStr))
            {
                within = double.Parse(withinStr) / 100;
            }

            if (within == 20)
            {
                foreach (var item in activeHousesNoPool.Value)
                {
                    var data = FlipsController.FlipByZip;
                    CalculateNeededValues(item, data, "zip");
                }
                return View(activeHouses.Value.OrderBy(x => x.PostalCode).ThenBy(x => x.LegalSubdivisionName));
            }
            else
            {
                var customList = new List<Listing>();
                var data = FlipsController.FlipByZipNoPool;
                foreach (var flipChar in data)
                {
                    var zip = flipChar.Zipcode;
                    var preflip = flipChar.PreFlip;
                    var min = -1.0 * within * preflip.Price;
                    var max = (1.0 + within) * preflip.Price;

                    foreach (var active in activeHousesNoPool.Value)
                    {
                        var myPrice = active.CurrentPriceValue();
                        if (myPrice >= min && myPrice <= max)
                        {
                            customList.Add(active);
                            CalculateNeededValues(active, data, "zip");
                        }
                    }
                }
                return View(customList.OrderBy(x => x.PostalCode).ThenBy(x => x.LegalSubdivisionName));
            }
        }
        
        public ActionResult BySubDivision()
        {
            foreach (var item in activeByDiv.Value)
            {
                var data = FlipsController.FlipBySubDivision;
                CalculateNeededValues(item, data, "subdiv");
            }
            return View(activeByDiv.Value.OrderBy(x => x.LegalSubdivisionName));
        }

        public ActionResult ByCommonSubDivision()
        {
            foreach (var item in activeByCommDiv.Value)
            {
                var data = FlipsController.FlipByCommonSubDivision;
                CalculateNeededValues(item, data, "subdiv");
            }
            return View(activeByDiv.Value.OrderBy(x => x.LegalSubdivisionName));
        }
        
        private static List<Listing> InitActiveHouses(Dictionary<string,List<Listing>> lookup=null)
        {
            //string path = HostingEnvironment.MapPath(
            //    string.Format("{0}/{1}", dataFolder, byZipFile));

            //string json = null;
            //using (var sr = new StreamReader(path))
            //{
            //    json = sr.ReadToEnd();
            //}
            //var array = JsonConvert.DeserializeObject<List<MlsRow>[]>(json);
            //var list = new List<MlsRow>();
            //foreach (var a in array)
            //{

WebSite/Controllers/MapsController.cs
using HouseFlipper.DataAccess.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace HouseFlipper.WebSite.Controllers
{
    public class MapsController : Controller
    {
        // GET = Maps
        public ActionResult ViewMaps()
        {
            // Add action logic here
            return View();
        }

        public ActionResult MapAddress()
        {
            return View();
        }

        public ActionResult GoogleMap()
        {
            return View();
        }

        public ActionResult GoogleMap2()
        {
            return View();
        }

        public ActionResult GoogleMap3()
        {
            return View();
        }

        public ActionResult GoogleMap4()
        {
            return View();
        }

        public ActionResult GoogleMap5()
        {
            return View();
        }

        public ActionResult GoogleMap6()
        {
            var markers = new List<Marker>() {
                new Marker()
                {
                    title = "Aksa Beach",
                    lat = "19.1759668",
                    lng = "72.79504659999998",
                    description = "Aksa Beach is a popular beach and a vacation spot in Aksa village at Malad, Mumbai.",
                    icon = "http://maps.google.com/mapfiles/ms/icons/yellow-dot.png"
                },
                new Marker()
                {
                    title = "Juhu Beach",
                    lat = "19.0883595",
                    lng = "72.82652380000002",
                    description = "Juhu Beach is one of favourite tourist attractions situated in Mumbai.",
                    icon = "http://maps.google.com/mapfiles/ms/icons/orange-dot.png"
                },
                new Marker()
                {
                    title = "Girgaum Beach",
                    lat = "18.9542149",
                    lng = "72.81203529999993",
                    description = "Girgaum Beach commonly known as just Chaupati is one of the most famous public beaches in Mumbai.",
                    icon = "http://maps.google.com/mapfiles/ms/icons/green-dot.png"
                },
                new Marker()
                {
                    title = "Jijamata Udyan",
                    lat = "18.979006",
                    lng = "72.83388300000001",
                    description = "Jijamata Udyan is situated near Byculla station is famous as Mumbai (Bombay) Zoo.",
                    icon = "http://maps.google.com/mapfiles/ms/icons/red-dot.png"
                },
                new Marker()
                {
                    title = "Sanjay Gandhi National Park",
                    lat = "19.2147067",
                    lng = "72.91062020000004",
                    description = "Sanjay Gandhi National Park is a large protected area in the northern part of Mumbai city.",
                    icon = "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"
                }
            };            
            return View(markers);
        }
    }
}

WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - House Flipper</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("House Flipper", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Listings", "Index", "Listings")</li>
                    @*<li>@Html.ActionLink("Flips", "Index", "Flips")</li>
                        <li>@Html.ActionLink("ZipCode", "ByZip", "Flips")</li>
                        <li>@Html.ActionLink("SubDivision", "BySubDivision", "Flips")</li>
                        <li>@Html.ActionLink("CommonSubDiv", "ByCommonSubDivision", "Flips")</li>*@

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Flips<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("All", "Index", "Flips")
                            </li>
                            <li>
                                @Html.ActionLink("Zipcode", "ByZip", "Flips")
                            </li>
                            <!--
                            <li>
                                @Html.ActionLink("Subdivision", "Subdivision", "Flips")
                            </li>
                            <li>
                                @Html.ActionLink("ZipCode>NoPool", "ByZipNoPool", "Flips")
                            </li>
                            <li>
                                @Html.ActionLink("ZipCode>WithPool", "ByZipWithPool", "Flips")
                            </li>
                            <li>
                                @Html.ActionLink("SubDivision>NoPool", "BySubDivisionNoPool", "Flips")
                            </li>
                            <li>
                                @Html.ActionLink("SubDivision>WithPool", "BySubDivisionWithPool", "Flips")
                            </li>
                            <li>
                                @Html.ActionLink("Common SubDivision>NoPool", "ByCommonSubDivisionNoPool", "Flips")
                            </li>
                            <li>
                                @Html.ActionLink("Common SubDivision>WithPool", "ByCommonSubDivisionWithPool", "Flips")
                            </li>
                                -->
                        </ul>
                    </li>


                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Active<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("All", "Index", "Active")
                            </li>
                            <!--
                            <li>
                                @Html.ActionLink("ZipCode>NoPool", "ByZipNoPool", "Active")
                            </li>
                            <li>
                                @Html.ActionLink("ZipCode>WithPool", "ByZipWithPool", "Active")
                            </li>
                            <li>
                                @Html.ActionLink("SubDivision>NoPool", "BySubDivisionNoPool", "Active")
                            </li>
                            <li>
                                @Html.ActionLink("SubDivision>WithPool", "BySubDivisionWithPool", "Active")
                            </li>
                            <li>
                                @Html.ActionLink("Common SubDivision>NoPool", "ByCommonSubDivisionNoPool", "Active")
                            </li>
                            <li>
                                @Html.ActionLink("Common SubDivision>WithPool", "ByCommonSubDivisionWithPool", "Active")
                            </li>
                                -->
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Maps<b class="caret"></b></a>
                        <ul class="dropdown-menu">

                            <li>@Html.ActionLink("My City Maps", "ViewMaps", "Maps")</li>
                            <li>@Html.ActionLink("Map an Address", "MapAddress", "Maps")</li>
                            <li>@Html.ActionLink("Map1", "GoogleMap", "Maps")</li>
                            <li>@Html.ActionLink("Map2", "GoogleMap2", "Maps")</li>
                            <li>@Html.ActionLink("Map3", "GoogleMap3", "Maps")</li>
                            <li>@Html.ActionLink("Map4", "GoogleMap4", "Maps")</li>
                            <li>@Html.ActionLink("Map5", "GoogleMap5", "Maps")</li>
                            <li>@Html.ActionLink("Map6", "GoogleMap6", "Maps")</li>
                        </ul>
                    </li>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - House Flipper</p>
        </footer>
    </div>

    @*<script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyDMg0szYattzgj4r_yYBIGEfFtbUFKN6gE"></script>*@
    <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyDMg0szYattzgj4r_yYBIGEfFtbUFKN6gE"></script>
    @*<script type="text/javascript">

        $(document).ready(function () {
          initialize();
        });
        function initialize() {
          var mapOptions = {
            center: new google.maps.LatLng(6.9167, 79.8473),
            zoom: 10,
            mapTypeId: google.maps.MapTypeId.ROADMAP
          };
          var map = new google.maps.Map(document.getElementById("map_canvas"),
            mapOptions);
          // create a marker
          var latlng = new google.maps.LatLng(6.9167, 79.8473);
          var marker = new google.maps.Marker({
            position: latlng,
            map: map,
            title: 'My Place'
          });
        }
         </script>*@


</body>
</html>

WebSite/Views/Shared/_Layoutv2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>

    @RenderBody()

</body>
</html>